version: '3.9'

services:
  web:
    build: .
    container_name: blog_django_web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: /entrypoint.sh

volumes:
  static_volume:

